# Generated by Django 4.1.4 on 2022-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolder', models.CharField(max_length=100, verbose_name='Владелец карточки')),
                ('expirationDate', models.DateField(max_length=100, verbose_name='Дата истечения срока')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Баланс')),
                ('lastFourDigigts', models.PositiveIntegerField(default=0, verbose_name='Последние четыре цыфры')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карта',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100, verbose_name='Цель')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Бюджет')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цель',
            },
        ),
    ]
